# 注音鍵盤配置
BopomofoKeyboardLayout=standard
# 選字窗樣式
CandidateLayout="Not Set"
# 選字鍵
SelectionKeys=123456789
# 選字鍵
SelectionKeysCount=9
# 使用空白鍵選字
ChooseCandidateUsingSpace=True
# 選字時，候選詞起算點
SelectPhrase=before_cursor
# 選字後自動移動游標
MoveCursorAfterSelection=False
# 選字時
AllowMovingCursorWhenChoosingCandidates="Moving cursor is not allowed"
# ESC 按鍵清除輸入緩衝區的所有內容
EscKeyClearsEntireComposingBuffer=False
# 在大寫鎖定時也能輸入中文（像微軟新注音）
capsLockAllowChineseInput=False
# Shift + 字母按鍵
ShiftLetterKeys=directly_output_uppercase
# 使用 Shift + Enter 按鍵輸入聯想詞
ShitEnterEnabled=True
# 重複輸入標點時，輸入下一個候選標點符號
RepeatedPunctuationToSelectCandidateEnabled=False
# Control + Enter 按鍵
KeyHandlerCtrlEnter=disabled
# 在輸入法選單中顯示「注音字型破音字標記模式」開關
ShowBopomofoFontAnnotationSupportInMenu=False
# 開啟自訂詞庫檔案要用
OpenUserPhraseFilesWith=xdg-open
# 加詞腳本路徑
AddScriptHookPath=/usr/share/fcitx5/data/mcbopomofo-add-phrase-hook.sh
# 在加入新詞之後執行加詞腳本
AddScriptHookEnabled=False
# 啟用半形標點符號
HalfWidthPunctuationEnable=False
# 啟用聯想詞功能
AssociatedPhrasesEnabled=False
# Enable Bopomofo Font Annotation Support
BopomofoFontAnnotationSupportEnabled=False

